In [2]:
# 1 Import the numpy package under the name np (★☆☆)

import numpy as np

In [3]:
# 2 Print the numpy version and the configuration (★☆☆)

print(np.__version__)

1.18.1


In [5]:
# 3 Create a null vector of size 10 (★☆☆)

vektor = np.zeros(10)
print(vektor)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 4 How to find the memory size of any array (★☆☆)

print(vektor.size * vektor.itemsize)  # rumus size memory of array
                                      # vektor.size utk mendapatkan number of element
                                      # vektor.itemsize utk mendapatkan byte size of element

80


In [10]:
# 5 How to get the documentation of the numpy add function from the command line? (★☆☆)

In [3]:
# 6 Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

vektor = np.zeros(10)  # Buat vektor dgn nilai 0 size nya 10. Dengan function zeros
vektor[4]=1            # Nilai ke-5 atau index ke-4 diganti dgn 1
print(vektor)
print(vektor.size)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
10


In [107]:
# 7 Create a vector with values ranging from 10 to 49 (★☆☆)

vektor = np.arange(10,50)  # Membuat vektor / 1d array dgn nilai 10-49 dgn function arange(10,50)
print(vektor)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [108]:
# 8 Reverse a vector (first element becomes last) (★☆☆)

# print(vektor[::-1])
print(np.flipud(vektor))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [102]:
?np.flipud
# Flip the entries in each column in the up/down direction.
# Rows are preserved, but appear in a different order than before.

In [29]:
# 9 Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

vektor = np.arange(0,9).reshape(3,3)  # Use arange function with parameter (0,9).
print(vektor)                         # Then, use function reshape(3,3) to change vector to matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# 10 Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

vektor = [1,2,0,0,4,0]
print(np.nonzero(vektor))  # Jadi guna dri nonzero ini utk me-return index dri elemen yg nilainya bukan 0 dlm suatu array

(array([0, 1, 4], dtype=int64),)


In [109]:
?np.nonzero
# Me-return index dari nilai selain 0 dalam suatu array

In [5]:
# 11 Create a 3x3 identity matrix (★☆☆)

mat_identitas = np.eye(3)  # Bisa juga pake np.identity()
print(mat_identitas)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [113]:
?np.random.random
# Return random floats in the half-open interval (0.0, 1.0)

In [50]:
# 12 Create a 3x3x3 array with random values (★☆☆)

matrix = np.random.random((3,3,3))  # Jadi guna random.random ni utk me-return float secara random dgn interval 0-1 
print(matrix)                       # Kita tinggal tambahin aja shape array nya mau seperti apa

[[[0.69379359 0.65008278 0.97043771]
  [0.85733937 0.532073   0.07532906]
  [0.79502595 0.49874574 0.10010693]]

 [[0.8587551  0.92272712 0.01734737]
  [0.65674431 0.65623686 0.53587682]
  [0.48076851 0.05783349 0.84855822]]

 [[0.17513655 0.34448449 0.78589556]
  [0.74082978 0.73157945 0.13983786]
  [0.16671387 0.49592542 0.55907129]]]


In [44]:
# 13 Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

matrix = np.random.random((10,10))
print(matrix)
print(f'Max value in array: {matrix.max()}')
print(f'Min value in array: {matrix.min()}')

[[0.25462894 0.93969094 0.43161061 0.30013394 0.94737048 0.98682626
  0.60165303 0.48769136 0.1447942  0.86898161]
 [0.62146789 0.43380968 0.5737588  0.70060397 0.59705808 0.67595506
  0.24895019 0.74622274 0.46658086 0.10513204]
 [0.21937205 0.19965216 0.67568875 0.35701917 0.1073994  0.84534867
  0.16626208 0.81133314 0.11813557 0.32673887]
 [0.24874801 0.3621933  0.11025766 0.16351217 0.22434924 0.90670897
  0.24194272 0.30480621 0.16583896 0.21896714]
 [0.58814163 0.61062998 0.08888722 0.8779074  0.28250409 0.68884251
  0.02333013 0.18661632 0.52878351 0.22056769]
 [0.38985541 0.73730634 0.14906946 0.76706762 0.08370315 0.41360347
  0.80485162 0.09608883 0.6844489  0.58125741]
 [0.03506958 0.92179292 0.43593371 0.19757577 0.71469227 0.67627013
  0.35850162 0.7708331  0.99744599 0.11776021]
 [0.64869241 0.40716947 0.78520092 0.65331441 0.97944893 0.99947
  0.0637705  0.04693311 0.32222679 0.33804886]
 [0.98351567 0.45308826 0.08510653 0.79244969 0.50407587 0.88941937
  0.33398283 0.

In [6]:
# 14 Create a random vector of size 30 and find the mean value (★☆☆)

vektor = np.random.random(30)
print(vektor)
print(f'Mean of this array: {np.mean(vektor)}') # Guna mean utk mencari mean dlm suatu array

[0.47672299 0.70309895 0.64775567 0.18536307 0.57349405 0.67959493
 0.00955034 0.97110271 0.32910135 0.39075683 0.66862808 0.09378754
 0.01112007 0.85350143 0.79479019 0.80478689 0.47708753 0.01036736
 0.50559089 0.27761771 0.87128603 0.51094927 0.45181108 0.9710539
 0.37666674 0.78945901 0.50100067 0.51412889 0.08480302 0.38418055]
Mean of this array: 0.49730525774520823


In [11]:
# 15 Create a 2d array with 1 on the border and 0 inside (★☆☆)

x = np.ones((6,6), dtype=np.int)  # Buat array with ones value
print(x)
print(x.size)
print('\n')
x[1:-1, 1:-1]=0   # Assign nilai 0 pada baris 1-5 dan kolom 1-5 dgn slicing
print(x)
print(x.size)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
36


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
36


In [62]:
# dri ka Alfa
# Create a 2d array with 7 in all value

matrix1 = np.full((4,3),7)  # Guna full utk buat array dengan 1 elemen tertentu, kita masukan shape array nya dan 1 elemen nya
matrix2 = np.ones((4,3), dtype=np.int) * 7  # Buat dlu array ones value lalu dikali 7
print(matrix1)
print('\n')
print(matrix2)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
# 16 How to add a border (filled with 0's) around an existing array? (★☆☆)

matrix = np.random.randint(1,9,9).reshape(3,3)  # Buat dlu array, sembarang aja tapi shape nya simetris e.g (3,3)
print(matrix)
print(matrix.size) # Size matrix awal, sebelum di-lapisi border
print('\n')
matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)  # Like kita mau melapisi existing array with border angka 0
print(matrix)
print(matrix.size) # Size matrix setelah di-lapisi border

[[5 8 2]
 [4 5 8]
 [5 7 6]]
9


[[0 0 0 0 0]
 [0 5 8 2 0]
 [0 4 5 8 0]
 [0 5 7 6 0]
 [0 0 0 0 0]]
25


In [9]:
?np.pad

In [90]:
# 17 What is the result of the following expression? (★☆☆)

# 0 * np.nan # --> not a number (NaN)
# np.nan == np.nan # --> is always False
# np.inf > np.nan # --> False because np.nan is not a number
# np.nan - np.nan # --> nan
# np.nan in set([np.nan]) # --> True
# 0.3 == 3 * 0.1 # --> False

In [93]:
# 18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
matrix = np.diag((1,2,3,4,5))  # Guna diag disini utk membuat array zeros value dgn diagonal tertentu
print(matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
?np.diag
# Extract a diagonal or construct a diagonal array.
# Jadi diag ni bisa digunakan utk meng-ekstrak diagonal suatu array
# Dan bisa juga digunakan utk membuat array dgn diagonal tertentu

In [18]:
# 19 Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

matrix = np.zeros((8,8), dtype=np.int)  # Buat dlu array zeros value, size 8x8
matrix[1::2, ::2] = 1  # Assign nilai 1 pd baris 1-8 longkap 2, kolom 0-8 longkap 2 dgn slicing
matrix[::2, 1::2] = 1  # Assign nilai 1 pd baris 0-8 longkap 2, kolom 1-8 longkap 2 dgn slicing
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
# 20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

np.unravel_index(100, (6,7,8))  # Jadi unravel_index tu utk mengonversi indeks datar atau larik indeks datar menjadi tupel dari koordinat array.
                                # Contoh disitu kita mau cari index dri elemen ke-100 dalam matrix yg berbentuk (6,7,8)

(1, 5, 4)

In [6]:
?np.unravel_index