In [1]:
import numpy as np

In [8]:
# CREATE MATRIX

a = np.array(([1,2,3],[4,5,6]))
a

array([[1, 2, 3],
       [4, 5, 6]])

## Transpose matrix

In [5]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Flatten matrix, ubah array 2d jadi 1d

In [6]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

## Reshape

In [11]:
a.shape 

(2, 3)

In [9]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a.reshape(6,1)  # Reshape itu perubahannya not inplace, lalu ubahan nilai nya harus sama dgn jumlah elemen dri array tsb
                # 6 x 1 = 6

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [12]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

## Resize

In [ ]:
# Resize itu sama dengan reshape tetapi perubahannya inplace, tidak me-return

In [14]:
a.shape   # Shape sebelum resize

(2, 3)

In [15]:
a.resize(3,2)

In [16]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a.shape  # Shape sesudah resize

(3, 2)