In [1]:
import numpy as np

In [8]:
# Coba gabung 2 array 1d

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

# Nah sekarang kita mulai gabungin
# Gabungin nya ada 2 macam, gabung secara vertikal atau horizontal

# Kita gabung horizontal dulu

c = np.hstack((a,b))  # Kalo case gini, digabung horizontal, hasilnya array 1d
print('Gabung horizontal:', c)

# Sekarang kita gabung vertikal

d = np.vstack((a,b))  # Kalo case gini, digabung vertikal, hasilnya array 2d
print('Gabung vertikal:')
print(d)

[1 2 3]
[4 5 6]
Gabung horizontal: [1 2 3 4 5 6]
Gabung vertikal:
[[1 2 3]
 [4 5 6]]


In [19]:
# Coba gabung 2 array 2d

a = np.zeros((2,3))
b = np.ones((2,3))
print('a:')
print(a)
print('b:')
print(b)

# Nah kita coba gabung

# Secara horizontal dulu

c = np.hstack((a,b))
print('Gabung horizontal:')
print(c)

# Secara vertikal

d = np.vstack((a,b))
print('Gabung vertikal:')
print(d)

a:
[[0. 0. 0.]
 [0. 0. 0.]]
b:
[[1. 1. 1.]
 [1. 1. 1.]]
Gabung horizontal:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
Gabung vertikal:
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# Coba gabung 2 array 3d

a = np.zeros((2,3,4))
b = np.ones((2,3,4))
print('a:')
print(a)
print('b:')
print(b)

# Gabung secara horizontal
c = np.hstack((a,b))
print('Gabung horizontal:')
print(c)

# Gabung secara vertikal
d = np.vstack((a,b))
print('Gabung vertikal:')
print(d)

a:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
b:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Gabung horizontal:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Gabung vertikal:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
